# Generated by Django 5.2 on 2025-04-23 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_position_employee_address_employee_birthday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('request_body', models.JSONField()),
                ('request_headers', models.JSONField()),
                ('response_body', models.JSONField()),
                ('response_headers', models.JSONField()),
                ('status_code', models.IntegerField()),
                ('is_senstive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_executed_by', to='employees.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['-created_at'], name='logs_created_at_idx')],
            },
        ),
    ]
