# Generated by Django 5.2 on 2025-04-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_position_employee_address_employee_birthday_and_more'),  # noqa
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('basic', 'Básico')], default='basic', max_length=40, null=True),  # noqa
        ),
    ]
