# Generated by Django 5.2 on 2025-04-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # noqa
                ('card_id', models.CharField(max_length=100, primary_key=True, serialize=False)),  # noqa
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('request_type', models.CharField(max_length=100)),
                ('recipient', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=255)),
            ],
        ),
    ]
