# Generated by Django 5.2 on 2025-04-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='id',
            new_name='card_id',
        ),
    ]
