# Generated by Django 5.2 on 2025-04-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_rename_id_card_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
