# Generated by Django 5.2 on 2025-04-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_card_card_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_id',
        ),
        migrations.AddField(
            model_name='card',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='google_user_id',
            field=models.CharField(db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
